.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. cocabit_qt test_cocabit_qt
clean: FORCE
	$(MAKE) -C .. cocabit_qt_clean test_cocabit_qt_clean
check: FORCE
	$(MAKE) -C .. test_cocabit_qt_check
cocabit-qt cocabit-qt.exe: FORCE
	 $(MAKE) -C .. cocabit_qt
